### ISSUE TITLE
Write a new Experiments scenario with MNIST/Tensorflow

### ISSUE THREAD

**Issue by iesahin** [iterative/katacoda-scenarios#60]
[The current experiments scenario][expsc] uses [example-get-started][egs] project for presenting the Experiments. However most of the `train.py` commands fail due to out-of-memory errors in Katacoda. 

We need a new way to present experiments concepts: 

- It should depend on MNIST. In our previous discussion in #15, I tested Tensorflow/MNIST example and it worked on Docker on Katacoda. This is a good way to build and test the new example dataset. 

- Although there are other (and possibly more interesting) datasets like the [Fashion MNIST][fashion] or [Credit Card Fraud Detection][ccfraud], their requirements may be above what can be provided by Katacoda. Hence using the standard MNIST is preferable than venturing into these. 

Related to epic iterative/dvc.org#1400

This is also related to #55

[expsc]: https://katacoda.com/dvc/courses/get-started/experiments
[egs]: https://github.com/iterative/example-get-started

**Comment by iesahin** [comment]
The structure of the project will be similar to the current `example-get-started`. 

The usual way of distributing MNIST dataset (in [LeCun's website][lecun] and [deep.ai][deepai]) is in a format not directly usable by Python. Our `prepare.py` script will receive this data and convert it into a usable format. 

The data will be kept in the `data/` directory similar to the current one. The files will be downloaded from a DVC remote. There are 4 files unlike the current single one. 

[deepai]: https://deepai.org/dataset/mnist
[lecun]: http://yann.lecun.com/exdb/mnist/

The `featurize` step will be replaced by `normalize`. It will normalize, shuffle and prepare the vectors similar to [the script][script]. It can have `seed` and `ratio` parameters. We can also see the effects of normalization. 

[script]: https://gist.github.com/iesahin/f3a22ebca5b52579748dc7d724047c8d#file-tf-mnist-py-L12-L27

There will be a `model` dependency to `train`, that just returns the model. We'll have `Dense` layers with parameterized `units`, `activation` and a CNN layer with various parameters. 

The training will also receive various loss and optimizer parameters. 

The evaluation will use `checkpoint: true` for the experimentation.

**Comment by iesahin** [comment]
A preliminary `params.yaml` looks like this: 

```yaml
prepare:
  seed: 20210428
  remix: True
  remix_split: 0.20

preprocess:
  seed: 20210428
  normalize: True
  shuffle: False
  add_noise: False
  noise_amount: 0.0004
  noise_s_vs_p: 0.5

train:
  seed: 20210428
  validation_split: 0.2
  model: "mlp"
  optimizer: "Adam"
  loss: "SparseCategoricalCrossentropy" 
  epochs: 10
  batch_size: 128

model_mlp:
  units: 128
  activation: "relu"

model_cnn:
  dense_units: 128
  conv_kernel_size: 3
  conv_units: 32
  dropout: 0.5
```

There may be some others, I think the more parameters we have, the more freedom to experiment we can have while writing the documentation.
